### ISSUE TITLE
1936

### ISSUE THREAD

**Issue by korhon** [NKCR-INPROVE/evidence.periodik#10]
Ve výpisu dostupných čísel chybí rok 1936. Dá se s tím něco dělat?
s. 20 v aplikaci končí číslem 24.08.1935
s. 21 ukazuje pouze "meta_nazev: Lidové noviny - Vydání Brno; mutace: Brno; vydani: morning;"
s. 22 zase pokračuje 04.05.1937

**Comment by pavelkocourek** [comment]
mrkni se Miloši, kde je rozdíl v datech

**Comment by korhon** [comment]
Nemuzes to trochu rozvest? :)




 Od:   Pavel Kocourek <notifications@github.com> 
 Komu:   NKCR-INPROVE/evidence.periodik <evidence.periodik@noreply.github.com> 
 Kopie:   korhon <milos.korhon@vkol.cz>, Author <author@noreply.github.com> 
 Odesláno:   4.7.2018 9:13 
 Předmět:   Re: [NKCR-INPROVE/evidence.periodik] 1936 (#10) 


mrkni se Miloši, kde je rozdíl v datech

**Comment by albertoh** [comment]
Bude reseno v #18
