### ISSUE TITLE
Nesprávné zarovnávání v některých prohlížečích

### ISSUE THREAD

**Issue by zabak** [NKCR-INPROVE/evidence.periodik#101]
Chrome na MacOS, ale asi občas i jinde:
![image](https://user-images.githubusercontent.com/811537/69421603-c2b5d600-0d21-11ea-9194-a56ea9054b99.png)
![image](https://user-images.githubusercontent.com/811537/69421684-ee38c080-0d21-11ea-80dc-899c922435d0.png)

**Comment by albertoh** [comment]
Je to zpusobeno sirkou okna v prohlizece.

**Comment by zabak** [comment]
Není, viz

![image](https://user-images.githubusercontent.com/811537/72880846-f3a18f80-3cff-11ea-9f95-c647b0346cfe.png)

**Comment by zabak** [comment]
Respektive možná na to má vliv šířka okna, ale v tom případě je to špatně. V užším okně to udělá třeba toto:

![image](https://user-images.githubusercontent.com/811537/72881078-5f83f800-3d00-11ea-9f7e-f3cd7a6783b0.png)

**Comment by zabak** [comment]
Problém je způsoben tím, že delší názvy se zalomí a zvýší se tak výška karty, což ale v daném sloupci zabere i pozici karty pod tou aktuální. Buď řadit karty do sloupců a ne do řádků (šířka karty je fixní, výška nikoli), nebo zabránit změně výšky karet.

**Comment by zabak** [comment]
V případě prvního obrázku je potřeba změnit šířku daného sloupce

**Comment by pkudela** [comment]
Dobry den, aplikace zatim neni prizpusobena a vyladena na responsivni chovani, nebo ruzna rozliseni obrazovek. Je treba definovat alespon 3 nejcastejsi rozliseni obrazovek, ktera pouzivate (s predpokladem, ze browser bezi jako full screen, cili pres celou obrazovku). Jakmile toto budeme znat, tak muzeme prizpusobit chovani jednotlivych elementu s ohledem na rozliseni obrazovky, ci mobilni zarizeni.

**Comment by pkudela** [comment]
Dobry den, museli jsme kompletne prepsat casti aplikace a to z duvodu nevyhovujiciho frameworku ng2-materialize. Nyni UI aplikace plne vyuziva framework Angular Material. S timto krokem souvisi rada zmen, predevsim na strane UI a doufam, ze k Vasi spokojenosti, protoze se jedna jen o vylepseni pouzitelnosti aplikace. Je toho mnoho, ale ve zkratce zkusim popsat nektere zmeny:
----

- home page - nyni maji karty titulu fixni sirku, takze jiz nedochazi k jejich rozpadu, pocet karet na radku se prizpusobuje velikosti okna prohlizece viz. screenshot nize
![image](https://user-images.githubusercontent.com/16591052/75559902-94dcdd80-5a44-11ea-90c3-adae11a62f2e.png)
- responsivni chovani navigace
![image](https://user-images.githubusercontent.com/16591052/75560434-6dd2db80-5a45-11ea-84b7-3f6c259c633e.png)
- results - sjednoceni ikon v ramci cele aplikace, doplneni tooltipu, zmenseni radku, fixni header a paginace, vylepseni barev a designu, stridave radkovani, zvyraznovani radku po najeti mysi atd.
![image](https://user-images.githubusercontent.com/16591052/75560547-a7a3e200-5a45-11ea-89dd-8a8dd4b27579.png)
- results - moznost zabalit si dle potreby nektere sloupce
![image](https://user-images.githubusercontent.com/16591052/75560618-cd30eb80-5a45-11ea-9420-21c3fdc6aea8.png)
- editace svazku - zmenseni vysky radku, fixni paginace, nektere sloupce s fixni delkou (vami popisovany problem se sloupcem "datum"), sjednoceni ikon v ramci cele aplikace, vylepseni barev a designu
- editace vytisku - vylepseni layoutu, vzhledu, usporadani jednotlivych prvku atd.
![image](https://user-images.githubusercontent.com/16591052/75561021-914a5600-5a46-11ea-91a0-58aba9e2069a.png)
![image](https://user-images.githubusercontent.com/16591052/75561077-ade68e00-5a46-11ea-94c3-cbc9cbd344fb.png)
- dalsi stranky - sjednoceni layoutu, doplneni prekladu atd.
![image](https://user-images.githubusercontent.com/16591052/75561188-e1c1b380-5a46-11ea-83d6-807f3809d29e.png)
----
Pokud mate tu moznost, muzete porovnat se soucasnou starsi verzi aplikace.

**Comment by zabak** [comment]
Na hlavní stránce třetí řádek je uskočený
![image](https://user-images.githubusercontent.com/811537/77322521-270a9580-6d14-11ea-8903-6eefa3b1335e.png)

**Comment by zabak** [comment]
Vypadá to že je to vždy poslední řádek karet, který se nějak snaží vycentrovat ale nevychází to. Navrhuji pro zjednodušení odstranit centrování posledního řádku karet.

**Comment by pkudela** [comment]
Dobry den, ono to reseni nebude tak jednoduche, jak pisete, tak to nefunguje. Musime zjistit nejdrive pricinu, proc se tak deje. Podivam se na to a dam Vam vedet.

**Comment by zabak** [comment]
Prosím odstraňte z tohoto issue label ready for test, míček je na straně vývoje. V tomto issue prosím dořešme už jen ten uskočený třetí řádek na hlavní stránce, případné další problémy dáme do nových issues.

**Comment by albertoh** [comment]
Zarovnano
