### ISSUE TITLE
Posuvníky zasahují do záhlaví tabulek i do tlačítek pod tabulkou

### ISSUE THREAD

**Issue by zabak** [NKCR-INPROVE/evidence.periodik#102]
Pokud mám tabulku ve které se vertikálně scrolluje, tak posuvníky zahrnují i záhlaví tabulky i tlačítka pod tabulkou, i když se tyto části nescrollují.

**Comment by pkudela** [comment]
Dobry den, toto je vlastnost angular frameworku, ktera je dana a bohuzel ji nelze zmenit. Bez tohoto frameworku, bychom nedocilili pozadovane funkcionality tabulek, jako je napr. sticky header, footer, paginace, chovani checkboxu, sortovani apod.
