### ISSUE TITLE
PŘIHLÁŠENÍ

### ISSUE THREAD

**Issue by barinovak** [NKCR-INPROVE/evidence.periodik#103]
nefunkční přihlášení dle obvyklého způsobu, tudíž není možné ani ukládat vložená data

**Comment by zabak** [comment]
prosím nikdy nedávat přihlašovací údaje do veřejného githubu - zvlášť takovéto. Prosím autorku pokud to jde o smazání těch přihlašovacích údajů z textu výše a o změnu přihlašovacích údajů na testování.

**Comment by barinovak** [comment]
opraveno, smazáno! omlouvám se, vložila jsem z vlastních poznámek bez další kontroly!

**Comment by ludvicekj** [comment]
myslím, že přihlašování se změnilo kvůli správě uživatelů, issue #97
