### ISSUE TITLE
Nejde uložit nový svazek

### ISSUE THREAD

**Issue by barinovak** [NKCR-INPROVE/evidence.periodik#104]
Při pokusu o založení nového svazku Nové svobody se nepodařilo uložit svazek ani vygenerovat strukturu svazku
![obrazek](https://user-images.githubusercontent.com/40160250/77322119-85834400-6d13-11ea-9e28-e61a57d0b39a.png)
Vytvářeli jsme pod uživatelem barinova.

**Comment by ludvicekj** [comment]
u mě se již ukládá/ generuje bez problému.
