### ISSUE TITLE
Hodnoty filtru

### ISSUE THREAD

**Issue by habetpet** [NKCR-INPROVE/evidence.periodik#106]
Na stránce přehled exemplářů jsou hodnoty filtru **Vydání** vždy anglicky. Filtr **Vlastník** má jednu z hodnot `org.json.JSONArray:["VKOL","MZK","MZK","MZK","NKP"]`. Filtr **Stav** má jednu z hodnot `record.StavIssue.ChVV`.

![image](https://user-images.githubusercontent.com/39479150/77637324-c5396e00-6f55-11ea-9947-a997d3b5235b.png)

**Comment by albertoh** [comment]
Preklady opravene.
Hodnoty "org.json.JSSONArray..." a ChVV jsou v datech, stare pred opravou.

**Comment by habetpet** [comment]
Děkuji za vysvětlení. Předpokládám, že s novými daty to zmizí. Zavírám.
