### ISSUE TITLE
reload stránky s metatituly způsobí chybu

### ISSUE THREAD

**Issue by zabak** [NKCR-INPROVE/evidence.periodik#107]
Když vlezu na stránku s metatituly  (/permonik/titul) a dám reload tak Tomcat zahlásí error 404.

**Comment by albertoh** [comment]
Opraveno

**Comment by zabak** [comment]
Opraveno, ale stejná chyba je ještě na stránce /permonik/profile

**Comment by Chlupova** [comment]
Zavřít
