### ISSUE TITLE
Chybí texty pro fasetu - asi chyba v datech

### ISSUE THREAD

**Issue by zabak** [NKCR-INPROVE/evidence.periodik#109]
![image](https://user-images.githubusercontent.com/811537/85227231-70828380-b3dc-11ea-9085-9d558dcb82dc.png)
Opět z Lidové noviny - Vydání Brno. Možná je to jen chyba v datech, protože když na to kliknu, tak se začne něco stahovat ale nikdy to neskončí.

**Comment by habetpet** [comment]
Duplicitní k #106

**Comment by albertoh** [comment]
Data opravena. Ulozil jsem znovu cisla.
