### ISSUE TITLE
Exempláře VKOL

### ISSUE THREAD

**Issue by korhon** [NKCR-INPROVE/evidence.periodik#11]
U Lidových novin VKOL se chybně interpretuje počet exemplářů. Např. rok 1894 máme ve dvou svazcích,  
1894 2 LED-ČVN, čárový kód 2650364515
1894 2 ČVC-PROS, čárový kód 2650480142
Tedy: 
rok 1894, 2. ročník, leden-červen
rok 1894, 2. ročník, červenec-prosinec
Možno ověřit tady:
https://aleph.vkol.cz:443/F?func=direct&doc_number=000315244&local_base=SVK01&format=999

V Permonikovi se ale č.k. 2650364515 ukazuje pro celý rok až do prosince, takže se to chybně jeví, že druhou polovinu roku máme ve dvou exemplářích. V dalších letech to asi bude podobné.

**Comment by albertoh** [comment]
Bude reseno podle #18
