### ISSUE TITLE
Chybí překlad pro record.StavIssue.ChVV

### ISSUE THREAD

**Issue by zabak** [NKCR-INPROVE/evidence.periodik#110]
Vyskytuje se ve fasetě Stav

**Comment by habetpet** [comment]
Duplicitní k #106

**Comment by zabak** [comment]
Není to duplicitní, když je #106 už uzavřená :-)

**Comment by albertoh** [comment]
Stav ChVV je zastarala hodnota. Ted neni na seznamu moznych stavu. Zustal tam ze starych dat pred zmenou seznam stavu.
Uzaviram

**Comment by zabak** [comment]
OK, ale jak to z těch dat odstraníme?
