### ISSUE TITLE
Ruční zadávání data

### ISSUE THREAD

**Issue by korhon** [NKCR-INPROVE/evidence.periodik#112]
Při ručním zadání data v tabulce editace svazku (vlevo nahoře "datum od" a "datum do") se prohazuje den a měsíc. Např. ručně napíšu "1.7.1970" a při posunu tabulátorem na další pole se datum přepíše na "7. 1. 1970". Je otázka, jestli vůbec ruční zadání povolovat.

**Comment by albertoh** [comment]
Opraveno

**Comment by AnnaCajthamlova** [comment]
Miloši, pokud funguje, prosím uzavřít

**Comment by korhon** [comment]
Mám dovolenou, vůbec se na to nebudu dívat :)
Až po neděli 
 



 Od:   AnnaCajthamlova <notifications@github.com> 
 Komu:   NKCR-INPROVE/evidence.periodik <evidence.periodik@noreply.github.com> 
 Kopie:   korhon <milos.korhon@vkol.cz>, Author <author@noreply.github.com> 
 Odesláno:   10.8.2020 10:32 
 Předmět:   Re: [NKCR-INPROVE/evidence.periodik] Ruční zadávání data (#112) 


 
Miloši, pokud funguje, prosím uzavřít
