### ISSUE TITLE
Duplicitní čísla

### ISSUE THREAD

**Issue by korhon** [NKCR-INPROVE/evidence.periodik#113]
Při zpracování pražské mutace Svobodného slova (ČK 2650364742) vznikly duplicitní čísla. Nevíme jak, exemplář při některých změnách nejde ukládat (např. doplnit chybějící číslo 2, které reálně existuje), duplicity nezmizí ani při editaci svazku a ručním odškrtání checkboxů u nežádoucích čísel. 
![test2](https://user-images.githubusercontent.com/33937374/85515874-e6b20080-b5fd-11ea-80cf-1360953242ee.jpg)
Nevíme jak duplcicitu odstranit. Funguje funkce Smazat exemplář z přehledové tabulky, ale po ní zůstává volný řádek.
Ideálně by měly duplicity zmizet při editaci svazku, to ale nejde / nefunguje.

**Comment by albertoh** [comment]
Nedokazu rict jak se tam dostali duplicitni... 
Odstranil jsem issue: pri editaci zaznamu, zvolil jsem Smazat
![Screenshot (2)_LI](https://user-images.githubusercontent.com/5946836/85693065-35cb6480-b6d6-11ea-934a-24a82ac9ac79.jpg)
![Screenshot (4)_LI](https://user-images.githubusercontent.com/5946836/85693085-3a901880-b6d6-11ea-8090-47ae3ae2fcc9.jpg)

**Comment by barinovak** [comment]
Po uložení nového svazku, který se vygeneroval správně, se po jeho uložení vytvářejí v přehledové tabulce duplicitní čísla
![Poznámka 2020-07-16 115308](https://user-images.githubusercontent.com/40160250/87658220-2cc13680-c75c-11ea-95b2-79d0d9992adb.png)

**Comment by ludvicekj** [comment]
stejný problém u Mladé fronty. 
![objevujici-se-hvezdy_a-duplikace-císel](https://user-images.githubusercontent.com/40558551/88401909-a7c4c580-cdca-11ea-8b12-b6c9617834d1.png)

mohlo by to třeba být tím, že si moc hraji v jednom svazku? nebo nějakým špatným zadáváním dat?

**Comment by AnnaCajthamlova** [comment]
#139
