### ISSUE TITLE
Nefunguje ukládání

### ISSUE THREAD

**Issue by korhon** [NKCR-INPROVE/evidence.periodik#114]
Při vložení čísla mimo generovanou strukturu nejde uložit svazek. Nevíme tedy jestli je to zrovna tím, že je to mimo strukturu, ale při doplnění čísla 2 u Svobodného slova (ČK 2650364743) které reálně existuje, nejde uložit svazek. Nahoře běhá čára a nikdy nedoběhne. 
Exemplář nejde přidat ani přes funkci  "Přidat exemplář" v přehledové tabulce. Dialog lze vyplnit, ale po kliknutí na OK se nic neděje.

**Comment by albertoh** [comment]
Tomu moc nerozumim. Muzeme v pondeli?

**Comment by korhon** [comment]
Obecně jde o to, že si vygeneruju strukturu, která počítá s vydáváním každý den kromě neděle. A pak se v rámci zpracování svazku ukáže, že tam jedna neděle je. Při vložení tohoto čísla (zaštrnutím checkboxu v dosud prázdném řádku) nejde svazek uložit. Ale to je jenom vysvětlení, můžeme to nechat na pondělí.
