### ISSUE TITLE
Poslední číslo

### ISSUE THREAD

**Issue by korhon** [NKCR-INPROVE/evidence.periodik#115]
V tabulce editace svazku se při zadávání vyplňuje poslední číslo, které je ve svazku k dispozici. Ve svobodném slovu VKOL z roku 1970 (ČK 2650364743) je posledním číslem 75. Při uložení (pokud funguje) se ovšem toto číslo přepíše na 76 (ne u exempláře ale v tabulce vlevo nahoře). Proč?
![Snímek obrazovky (143)](https://user-images.githubusercontent.com/33937374/85518253-575a1c80-b600-11ea-9125-c88bdd004edf.png)

**Comment by albertoh** [comment]
Hodnota "posledni cislo" je orientativni, prave pro kontrolu vysledku.
V danem pripadu, od 3.1.1970 do 31.3.1970 je bez nedeli 75 dnu.

**Comment by zabak** [comment]
No právě - proč se tam zobrazuje 76, když poslední číslo je 75 a dnů bez nedělí je taky 75? Poslední číslo by mělo znamenat poslední existující čislo.

**Comment by korhon** [comment]
Poslední číslo zadávám při generování ručně. Je to vizuálně zjištěný a ověřený poslední výtisk ve svazku a slouží ke jenom ke kontrole, že to v pravé části mám vyplněné dobře. Takže při ukládání musím ověřit, že obě čísla odpovídají. Nic víc od toho nečekám, aspoň tak to chápu já.

**Comment by albertoh** [comment]
Omlouvam se, pochopil jsem to obracene. Podivam se na to prepsani te hodnoty.

**Comment by albertoh** [comment]
Opraveno

**Comment by AnnaCajthamlova** [comment]
Miloši, prosím otestovat a případně uzavřít, díky
