### ISSUE TITLE
nelze uložit Editaci výtisku

### ISSUE THREAD

**Issue by ludvicekj** [NKCR-INPROVE/evidence.periodik#117]
při změnách v editaci výtisku, nelze uložit změny.

![nelze ulozit editace výtisku](https://user-images.githubusercontent.com/40558551/85520855-bec59b80-b603-11ea-944c-d1b583ff974c.png)

**Comment by albertoh** [comment]
Nemuzu to reprodukovat.
Muzeme to probrat v pondeli

**Comment by ludvicekj** [comment]
nevím proč, ale dnes to funguje. 
zavírám.

**Comment by albertoh** [comment]
Opravil jsem to, ale nestihl jsem to rict :)
