### ISSUE TITLE
Vkládání metatitulu - nelze odstranit omylem vložený metatitul

### ISSUE THREAD

**Issue by zabak** [NKCR-INPROVE/evidence.periodik#118]
Pokud mám omylem vytvořený metatitul, mělo by být možné ho smazat, pokud je zcela prázdný

**Comment by ludvicekj** [comment]
v #96 se dohadovalo, že mazání by mělo spíš být v rukou nějakého superuživatele a ne nutně v grafickém rozhraní. v pondělí by se toto asi mělo projít v rámci diskuze o uživatelích a jejich právech dělat věci..

**Comment by zabak** [comment]
OK, tady zavírám.
