### ISSUE TITLE
Mutace se nezobrazuje v přehledu svazku i když je vyplněná

### ISSUE THREAD

**Issue by zabak** [NKCR-INPROVE/evidence.periodik#119]
![image](https://user-images.githubusercontent.com/811537/85834585-f2373000-b793-11ea-8060-a076940eda48.png)
![image](https://user-images.githubusercontent.com/811537/85834636-05e29680-b794-11ea-98ce-7a6a3ca549e9.png)

**Comment by AnnaCajthamlova** [comment]
prosím otestovat a případně uzavřít

**Comment by Chlupova** [comment]
Zavřít
