### ISSUE TITLE
Formulář přidání svazku po založení ročníku - nefunguje + úpravy

### ISSUE THREAD

**Issue by zabak** [NKCR-INPROVE/evidence.periodik#120]
DO formuláře by se automaticky měla přebírat z ročníku informace o vlastnictví, signatura, označení mutačního vydání a popis označení mutace

**Comment by zabak** [comment]
![image](https://user-images.githubusercontent.com/811537/85835837-067c2c80-b796-11ea-95b9-5c22caeef033.png)
Navíc by texty kolonek Chybějící strany a poškozené strany neměly být tlustě (to jen čísla těch stran) a měla by být za těmi názvy dvojtečka, tj. Chybějící strany: a Poškozené strany:

**Comment by zabak** [comment]
Navíc, když kliknu na OK, tak se nic nestane, nic ne neuloží, okno nezmizí

**Comment by zabak** [comment]
Možná nejlepší by bylo tento formulář zrušit. Je v něm něco, co se nedá udělat jinak?

**Comment by albertoh** [comment]
Formular zrusen

**Comment by Chlupova** [comment]
Zavřít
