### ISSUE TITLE
nekonzistentní linkování z hlavní stránky

### ISSUE THREAD

**Issue by zabak** [NKCR-INPROVE/evidence.periodik#121]
Když kliknu na hlavní stránce na metatitul maldá fronta, který má 0 výtisků (omylem čerstvě vytvořený) tak so dostanu jednou na jinou mladou frontu, jednou na Lidové noviny

![image](https://user-images.githubusercontent.com/811537/85838249-9374b500-b799-11ea-8900-54fd8c55e2f4.png)

![image](https://user-images.githubusercontent.com/811537/85838462-e9495d00-b799-11ea-9db9-43be15fcb7bf.png)

**Comment by zabak** [comment]
Už jsem to pochopil - když na to kliknu, tak se nejprve zobrazí něco jako "všechno" nebo předchozí seznam a pak se teprve aplikuje faseta. Což ale vzhledem k pomalejší reakci serveru způsobí, že vidím něco jiného něž čekám. Ale asi to není úplné vysvětlení. Každopádně toto není konzistentní chování a je to potřeba vyřešit

**Comment by Chlupova** [comment]
Zavřít
