### ISSUE TITLE
objevující se hvězdičky v mutačním vydání

### ISSUE THREAD

**Issue by ludvicekj** [NKCR-INPROVE/evidence.periodik#122]
vcelku náhodně a opakovaně se objevují u některých čísel hvězdičky označující mutační vydání. 
![image](https://user-images.githubusercontent.com/40558551/85920876-d311ce80-b877-11ea-8ef7-dd0575d1bfc1.png)

problém může být v tom, že jsem s těmito čísly zkoušel pracovat i jinde než v Editaci svazku, např. v Editaci výtisku, kde si onu hvězdičku vezme z pole Označení vydání místo z Označení mutačního vydání..
![image](https://user-images.githubusercontent.com/40558551/85920978-c0e46000-b878-11ea-9125-c4f9c82cdd70.png)

**Comment by albertoh** [comment]
Pole označující mutační vydání je editovaltelne jak ve editaci svazku i ve editaci vytisku (byl to pozadavek). Ono se muze odlisit od toho oznaceni pro cele metatitul.
Asi nekdo, nekdy pridal hvezdicku.

**Comment by ludvicekj** [comment]
problém je v tom, že i když jsem je smazal, či přepsal, opět se objevily. 
mohlo by to souviset se #137 ?

**Comment by albertoh** [comment]
Vidim.

**Comment by ludvicekj** [comment]
bohužel, stále se objevují. smažu je, uložím a stále tam jsou. možná mám špatně vložená data? 
![objevujici-se-hvezdy_a-duplikace-císel](https://user-images.githubusercontent.com/40558551/88402254-26216780-cdcb-11ea-8b7d-91d38e6423f3.png)

**Comment by AnnaCajthamlova** [comment]
Alberto, prosím o kontrolu - viz předchozí komentář Pepy, díky

**Comment by albertoh** [comment]
Problem souvisi s #137. Identifikator ted bere i oznaceni mutacniho vydani. Cisla se duplikovala (podle screenshotu). Reseni je zmazat neprotebne.
