### ISSUE TITLE
Přihlášený uživatel není úplně přihlášený ani odhlášený

### ISSUE THREAD

**Issue by zabak** [NKCR-INPROVE/evidence.periodik#125]
![image](https://user-images.githubusercontent.com/811537/85960226-4b74ae80-b9a2-11ea-954b-f9e76d16c342.png)

Do systému jsem se přihlásil v pátek, teď je neděle, jsem pořád přihlášený, zdá se. Reload stránky nezruší info o tom že jsem přihlášený apod. Když ale dám uložit, tak to zahlásí chybu "not logged". To je taky správně, domlouvali jsme timeout 8 hodin. Ale mělo by být jasné, jestli jsem nebo nejsem přihlášený. Obojí dohromady je špatně.

**Comment by albertoh** [comment]
Timeout nastaven na 8 hodin

**Comment by AnnaCajthamlova** [comment]
Petře, prosím otestovat a případně uzavřít, díky!

**Comment by Chlupova** [comment]
Zavřít
