### ISSUE TITLE
Vložit záznam z hlavního menu vkládá záznam s aktuálním datem

### ISSUE THREAD

**Issue by zabak** [NKCR-INPROVE/evidence.periodik#126]
...což nedává smysl. Zakládání záznamu pro současná vydání, navíc v den kdy to vydání vyjde, bude velmi vzácná činnost. Vede to jen ke zvýšení chybovosti, datum se navíc jako snad jediná věc nedá měnit.

**Comment by Chlupova** [comment]
Zavřít
