### ISSUE TITLE
Metatitul - je umožněno vložení duplicitního metatitulu

### ISSUE THREAD

**Issue by zabak** [NKCR-INPROVE/evidence.periodik#127]
Toto by mělo být ošetřeno přinejmenším upozorněním

**Comment by zabak** [comment]
Viz #130 ve skutečnosti se nový metatitul nevloží, jen se tam na chvíli (do reloadu stránky) objeví. Duplicity se ale dá dosáhnout tím, že se metatitul přejmenuje a uloží. Toto by nemělo být možné.

**Comment by Chlupova** [comment]
Zavřít
