### ISSUE TITLE
Vkládání metatitulu - poloha tlačítka

### ISSUE THREAD

**Issue by zabak** [NKCR-INPROVE/evidence.periodik#129]
Tlačítko na vložení metatitulu by mělo buď brát data z formuláře nad ním, nebo by mělo být jinde než pod tímto formulářem - je to matoucí.

**Comment by albertoh** [comment]
Prosim o vyjadreni. Podle me, je to v poradku tak jak je.
Kazdopadne, nesmi brat data z formulare nad nim.

**Comment by zabak** [comment]
Tlačítko "Vložit nový titul" umístit nad seznam metatitulů.

**Comment by albertoh** [comment]
Umisteno

**Comment by zabak** [comment]
Vyřešeno. zavírám
