### ISSUE TITLE
metatitul - chaos zadávání údajů

### ISSUE THREAD

**Issue by zabak** [NKCR-INPROVE/evidence.periodik#130]
Při vkládání počtu stran je možno šipkami naklikat záporné číslo. To je možné i uložit. Pokud ale postupně měním a ukládám počty stránek u různých metatitulů, tak mi to záhadně zobrazuje čísla která jsem zadal u jiných metatitulů. Postup:
Na začátku má Test1 1 stranu, Test2 2 strany a Test3 3 strany. Kliknu na Test3 a zadám 8 stran a uložím. Kliknu na Test2 a pak na Test3. Test3 ukazuje 3 strany. Dám reload a Test3 má 8 stran. Takto se asi chovají i ostatní pole.

**Comment by albertoh** [comment]
Pri reloadu se cela stranka nacte, a bude vybran prvni titul. Zobrazi se nejen pocet stran ale i vsechny udaje prvniho titulu.
Opravim zaporne cisla

**Comment by Chlupova** [comment]
Zavřít
