### ISSUE TITLE
zrušení vybraného metatitulu ve fasetě

### ISSUE THREAD

**Issue by zabak** [NKCR-INPROVE/evidence.periodik#132]
Pokud z hlavního menu jdu na nějaký titul a pak zruším fasetu s názvem metatitulu, vidím všechno. Je to požadované chování?  Pokud ano, měla by se v tom okamžiku objevit faseta metatitul, aby se dal vybrat jiný. To ale není možné. Faseta metatitul by neměla být zrušitelná, neměla by být ani vidět, protože název metatitulu je o řádek výš.

**Comment by albertoh** [comment]
Odstranim facetu metatitulu

**Comment by Chlupova** [comment]
Zavřít
