### ISSUE TITLE
Nekonzistentní navigace - počty záznamů

### ISSUE THREAD

**Issue by zabak** [NKCR-INPROVE/evidence.periodik#133]
![image](https://user-images.githubusercontent.com/811537/85961546-6dbefa00-b9ab-11ea-9c32-1acf17f2ad90.png)
![image](https://user-images.githubusercontent.com/811537/85961551-744d7180-b9ab-11ea-928d-7b3915353d57.png)

Systém sice stránkuje, ale neumožní zobrazit více než 500 prvních záznamů. Toto by nemělo být limitováno.

**Comment by Chlupova** [comment]
Zavřít
