### ISSUE TITLE
Kde se bere mutace a proč není ve fasetách?

### ISSUE THREAD

**Issue by zabak** [NKCR-INPROVE/evidence.periodik#134]
![image](https://user-images.githubusercontent.com/811537/85961598-c4c4cf00-b9ab-11ea-842d-09f99bafe462.png)
Když kliknu na hlavní stránce na Lidové noviny - Vydání Brno, tak se mi zobrazí seznam se záhlavím 
Metatitul: Lidové noviny - Vydání Brno Mutace: Brno. Kde se bere info o mutaci, proč je v záhlaví a není ve fasetě?

**Comment by Chlupova** [comment]
Zavřít
