### ISSUE TITLE
Nekonzistentní ukládání údajů exempláře: editace svazku vs. editovat exemplář z přehledu exemplářů

### ISSUE THREAD

**Issue by zabak** [NKCR-INPROVE/evidence.periodik#135]
Co zadám v jednom, neobjeví se v druhém nebo nějak divně. Týká se zejména výčtu stránek které jsou poškozené apod.

**Comment by zabak** [comment]
Navíc když jsou zadané chybějící nebo poškozené strany, tak to neznamená že se změní ikona, ta závisí na celkovém zatržítku dané vlastnosti. Mělo by být automatické.

**Comment by zabak** [comment]
Část problémů plyne asi z toho, že není intuitivně jasné, jestli člověk danou věc uložil. Hlavně v editaci svazku se snadno zapomene na kliknutí na Aktualizovat po zadání čísel stránek. Navíc tím že zatrhnu nebo odtrhnu tlačítko poškozené strany se mi nezobrazí i přehled stran, ten se rozbalí jen najetím kurzoru. Není tam jasná souvislost.

**Comment by zabak** [comment]
Pokud nějaké poškození zadám v editaci svazku, pak přejdu do editace výtisku a hledám to tam tak to nenajdu. Takže asi nefunguje to tlačítko Aktualizovat. Nebo Aktualizovat neznamená uložit?

**Comment by Chlupova** [comment]
Funguje. Zavřít
