### ISSUE TITLE
Přepisování uložených dat 

### ISSUE THREAD

**Issue by barinovak** [NKCR-INPROVE/evidence.periodik#137]
Při editaci nového svazku se při pokusu o vygenerování struktury dalšího mutačního výdaní jedné a té samé mutace stejného časového rozpětí načtená data přepíšou a zůstává v hlavní tabulce pouze jedno aktuálně vytvořené mutační vydání.
Př.: Svobodné slovo mutace Brno má VKOL ve dvou mutačních vydáních, a to se dvěma ** a bez značení.  Při editaci svazku se nejprve vygeneruje jedna struktura (**, led-břez, č. 1-76) a ačkoliv je svazek uložen pod svým unikátním čarovým kodem,  vytvořit  další svazek stejného rozpětí čísel, stejné mutace jen jiného mutačního vydání bez značení, se již nedaří a uložená data se přepisují.

**Comment by albertoh** [comment]
Problem je zpusoben tim, ze unikatnost vytisku byla kombinace poli id_titul, nazev, podnazev, vydani, mutace, datum_vydani.
Tj, oznaceni vydani (hvezdycky) nebylo na zacatku zadani pouzito.
Pridam

**Comment by albertoh** [comment]
Melo by to fungovat spravne.
