### ISSUE TITLE
Revize titulů

### ISSUE THREAD

**Issue by AnnaCajthamlova** [NKCR-INPROVE/evidence.periodik#139]
Prosím smazat tyto: Test1, Test2, Mladá fronta-b, Lidové noviny: Pražské vydání

Prosím označit jako "testovací": Lidové noviny - Vydání Brno, Mladá fronta, Mladá fronta - Praha, Svobodné slovo

@korhon co Hlasy z Dymokurska? Chcete je tam ponechat? 
@zabak souhlasí MZK?

**Comment by korhon** [comment]
Smazat. To jsem jenom zkousel zalozit metatitul. 





 Od:   AnnaCajthamlova <notifications@github.com> 
 Komu:   NKCR-INPROVE/evidence.periodik <evidence.periodik@noreply.github.com> 
 Kopie:   korhon <milos.korhon@vkol.cz>, Mention <mention@noreply.github.com> 
 Odesláno:   10.8.2020 10:53 
 Předmět:   [NKCR-INPROVE/evidence.periodik] Revize titulů (#139) 


 
Prosím smazat tyto: Test1, Test2, Mladá fronta-b, Lidové noviny: Pražské vydání 
Prosím označit jako "testovací": Lidové noviny - Vydání Brno, Mladá fronta, Mladá fronta - Praha, Svobodné slovo 
@korhon co Hlasy z Dymokurska? Chcete je tam ponechat?
 @zabak souhlasí MZK?

**Comment by Chlupova** [comment]
Ano souhlasime

**Comment by albertoh** [comment]
Smazal jsem Test1, Test2, Mladá fronta-b, Lidové noviny: Pražské vydání a Hlasy z Dymokurska

Jak chcete oznacit jako testovaci?

**Comment by zabak** [comment]
Když v záložce Metatituly přepíšu název metatitulu, tak se rovnou změní i v menu nalevo a navíc když pak kliknu na Home, tak je změněný i tam. Ale nikam se to neuloží a když příště kliknu na Metatituly tak je tm zase původní název. Buď by mělo jít metatitul z té obrazovky měnit nebo ne, ale když jde jen změnit ale ne už uložit, tak to nedává smysl.

![image](https://user-images.githubusercontent.com/811537/94002796-ab5cd480-fd9a-11ea-9196-3cdd6e2f4ffa.png)
![image](https://user-images.githubusercontent.com/811537/94002811-b283e280-fd9a-11ea-82b8-2cba27e144c4.png)

Co se týče toho označení jako testovací, tak jedna možnost je úprava názvu, ale lepší by byl příznak, který mj. způsobí, že daná věc nebude na hlavní stránce bez přihlášení vidět.

**Comment by zabak** [comment]
Zatím nebudeme řešit, zavírám.
