### ISSUE TITLE
Oprávnění k metatitulům

### ISSUE THREAD

**Issue by zabak** [NKCR-INPROVE/evidence.periodik#141]
Oprávnění vytvářet nebo měnit metatituly by měl mít jen admin nebo by na to mělo být speciální oprávnění.

**Comment by albertoh** [comment]
Prava ma jen admin

**Comment by zabak** [comment]
Pokud není uživatel přihlášený, neměl by vůbec vidět v menu položku Metatituly, stejně nemá právo s ní nic dělat. Ani přihlášený uživatel by ji neměl vidět.

**Comment by zabak** [comment]
...pokud není admin, protože taky nemá právo s ní nic dělat, jen ho mate kvůli tomu, že se dá přepsat a ta změna se dočasně projeví i na hlavní stránce.

**Comment by zabak** [comment]
Pokud bude u metatitulu textová anotace a prolink, odvolávám požadavek na odstranění menu metatitul pro nepřihlášeného uživatele.

**Comment by zabak** [comment]
Řeší se v #169, zde zavírám
