### ISSUE TITLE
Výběr symbolů mutačních vydání

### ISSUE THREAD

**Issue by korhon** [NKCR-INPROVE/evidence.periodik#147]
Symboly označující mutační vydání by měly být vybírány z přednastavené nabídky symbolů:
Hvězdička
Čtvereček
Tečka
atd.
Jde hlavně o to, že symboly (např. tečka, bod, puntík) je možné zadat v různé podobě a pak by stejné mutační vydání mohlo v různých knihovnách být označeno jinak a tudíž by se nepropojilo.
Např. při zpracování ČS Sportu se musí zadat čtvereček, což bylo řešeno přes vložení symbolu ve wordu a následné zkopírování přes schránku. Což asi není dobře. Viz obrázek
![image](https://user-images.githubusercontent.com/33937374/93758319-833d6c00-fc08-11ea-8027-cdb80d63e659.png)

Současně je nutno dořešit, jak naložit s různými variantami tohoto zápisu - plný nebo prázdný čtvereček atd.

**Comment by AnnaCajthamlova** [comment]
zůstává rejstřík znaků z metatitulu
