### ISSUE TITLE
Šířka sloupce pro označení mutačního vydání

### ISSUE THREAD

**Issue by korhon** [NKCR-INPROVE/evidence.periodik#148]
Pokud je mutační vydání označeno více symboly, pak se nevejde do šířky sloupce. Šířka sloupce by měla být pohyblivá podle toho, kolik znaků je potřeba.
V případě ČS Sportu se objevilo vydání s pěti čtverečky, které se tam v původní velikosti nevejdou a všechny se nezobrazí.
![image](https://user-images.githubusercontent.com/33937374/93759039-c77d3c00-fc09-11ea-9bdc-fd6449459ec3.png)

**Comment by albertoh** [comment]
Opraveno
