### ISSUE TITLE
 Vložení nového výtisku 

### ISSUE THREAD

**Issue by barinovak** [NKCR-INPROVE/evidence.periodik#152]
Stále není možné vložit nový výtisk mimo vygenerovanou strukturu. Při pokusu o přidání mimořádného čísla přes editaci svazku nelze číslo uložit a nový výtisk není možné vytvořit ani cestou přes "vložit záznam". 
Př. Čsl. Sport, neděle 13. 3. 1966 mimořádné číslo.
Problém nastává také v případě označení čísla. Tento konkrétní nedělní výtisk je na titulní straně značen pouze jako mimořádné číslo a příslušný checkbox určený pro číslo výtisku zůstává tedy prázdný, což se zobrazuje jako chyba.
![test3](https://user-images.githubusercontent.com/40160250/93880520-e77e2f80-fcdd-11ea-9cd2-832eaf69b1b7.png)

**Comment by albertoh** [comment]
Jestli to chapu spravne, musim zrusit povinnost pole "cislo"? Danne "mimoradni cislo" jak se bude lisit od "normalniho"? 
Unikatnost je urcena pomoci poli "id_titulu", "nazev", "podnazev", "vydani", "mutace", "datum_vydani", "znak_oznaceni_vydani"
Pro mimoradne vydani toho sameho dne by byla vsechna tato pole stejna. Mohlo by se odlisit pomoci "vydani"

**Comment by korhon** [comment]
To bude ještě potřeba probrat. Ideální by bylo připustit i jinou možnost zápisu než je prosté číslo. Protože v mimořádném vydání číslo zkrátka není. Možná by bylo řešením, že když nebude uvedeno číslo, musí být povinně vyplněno vydání, kde vyberu z nabídky mimořádné a na základě tohoto kroku se do pole "číslo" automaticky doplní např. pomlčka.
Taky může existovat mimořádné vydání, které číslováním zapadne do běžné řady, ale v tom případě by se pak postupovalo normálně.

**Comment by AnnaCajthamlova** [comment]
pokud u mimořádného čísla není hodnota čísla uvedena, může zůstat prázdné - není to chyba
