### ISSUE TITLE
Zrušit položku "Editovat issue"

### ISSUE THREAD

**Issue by korhon** [NKCR-INPROVE/evidence.periodik#153]
V tabulce "Editace svazku" navrhujeme zrušit položku "Editovat issue". Hlavně proto, že vlastně jen opakuje úkony prováděné v jednotlivých polích tabulky, připadá nám tam navíc.
Je ovšem pravda, že tato tabulka nabízí jedinou možnost, jak zapsat tyto informace:
Id bib záznamu 
Url bib záznamu
Uuid čísla
URL Krameria

To by se dalo ošetřit přidáním čtyř řádků na konec tabulky vlevo nahoře, pod položku "Poznámka". Provazba na knihovní katalog se bude hodit, u Krameria to ovšem bude narážet na praktickou nemožnost dohledat v digitální knihovně přesnou mutaci titulu, natož mutačního vydání.
Otázkou, zda je běžný operátor schopen zadat uuid čísla, se raději nezabývám. Já to neumím...

**Comment by zabak** [comment]
přebírání z Krameria jsme zatím neřešili, ale ideální by bylo že zadám uuid titulu, stáhne se mi komplet metadatový strom a předvyplní se maximum možného automaticky

**Comment by AnnaCajthamlova** [comment]
Zrušit "editovat issue" včetně těch čtyř odkazů
