### ISSUE TITLE
připomínky MZK 

### ISSUE THREAD

**Issue by Chlupova** [NKCR-INPROVE/evidence.periodik#17]
Posilame pripominky MZK k databazi Evidence periodik "Permonik" - Lidove noviny
- chybi nam v nabidce vlastnik MZK - prosime, co nejrychleji doplnit,at muzeme testovat
- v nabidce roku chybí rok 1936, ktery chceme testovat
- vystup z uprav by mohl byt v nabidce, at se nevracime sipkou zpet, vzdy na zacatek a na nejstarsi rok
- v nabidce moznost mazani zaznamu
- u exemplaru u jednotlivych vlastniku neni potreba zobrazovat CK v tabulce, ale az v rozkliknuti exemplare¨
- hledani púres "lupu" na liste nefunguje
- zobrazovane sloupce na rok a pocet stran jsou zbytecne prilis siroke 
- zrealizovat slibene propojeni na - databazi Pruzkumu fondu, VDK, RD
- moznost rozkliknuti na upravy jednotky primo ze sloupce exemplare (nyni zde CK)
- jak a kde označím napr. poskozeni strany 5 a roztrzena strana 7-8, kdyz se mi nerozbali jednotlive strany v cisle?
- regulovat sirku slouce s exemplari u vlastnika podle aktualniho poctu exemplaru (zbytecne siroke)
Radka Chlupova
Vera Jelinkova

**Comment by pavelkocourek** [comment]
Zavřeno na schůzce 22.10. v CDH
