### ISSUE TITLE
Exempláře NK - chybné přiřazení čárových kódů

### ISSUE THREAD

**Issue by AnnaCajthamlova** [NKCR-INPROVE/evidence.periodik#18]
U 17. července 1937 NK se ukazují tyto čárové kódy:
1003580492 - to je červenec-září 1936
1003580493 - říjen-prosinec 1936
1003580495 - duben-červen 1937

Všechny jsou chybně

**Comment by albertoh** [comment]
Toto vsechno je dusledek chybne zpracovani zaznamu z formatu vdk-setu.
Menit aplikaci tak, aby byl jeden krok pred importem zaznamu z vdk-setu:
 1.- cteni zaznamu z url
 2.- zpracovani podle parametru
 3.- zobrazeni vysledku v tabulce pro jejich nasledne upresneni
 4.- import vybranych exemplaru se spravnymi parametry

**Comment by ludvicekj** [comment]
čárové kódy NKP jsou správně.
