### ISSUE TITLE
Vydání 

### ISSUE THREAD

**Issue by AnnaCajthamlova** [NKCR-INPROVE/evidence.periodik#19]
Nefunguje možnost duplikovat datum pro doplnění více vydání - př. v jeden den vyšlo ranní a večerní vydání - nelze zaznamenat.

**Comment by albertoh** [comment]
Jestli to dobre pochopim, chceme pridat tlacitko "pridat vydání", aby se duplikoval pro vybrane datum?

**Comment by ludvicekj** [comment]
ano, myslíme to samé. chceme, aby bylo více vydání (ranní, večerní) se stejným datem, takže by se ve vyhledávání zobrazili dva řádky s jedním datem. (podobně jako je tomu u Lidové noviny - Vydání Brno ze dne 14. 6. 1937 - které jsme pro ilustraci vytvořili z čísla 15. 6. 1937.)

**Comment by AnnaCajthamlova** [comment]
Tlačítko tam je, ale nefunguje

**Comment by albertoh** [comment]
Muzete mi popsat, co se deje u Vas? Jaky pouzivate prohlizec?
