### ISSUE TITLE
Filtrování - časové rozhraní 

### ISSUE THREAD

**Issue by AnnaCajthamlova** [NKCR-INPROVE/evidence.periodik#2]
Filtrování časového rozhraní nenabízí celý rozsah let - vždy jen omezené rozhraní let (př. 1822-1842). Pokud chce uživatel jiný rok, musí složitě překlikávat. 
Doporučuji také vložit možnost vepsání data.

**Comment by albertoh** [comment]
Zmenil jsem kalendar na vyber roku. Na schuzce bylo receno, ze budeme chtit videt cele roky.
Pokud je to tak, uzavrete, prosim.
