### ISSUE TITLE
Pořadí sloupců

### ISSUE THREAD

**Issue by AnnaCajthamlova** [NKCR-INPROVE/evidence.periodik#20]
Mělo by být:
datum - vydání - číslo výtisku - počet stran 
viz zápis z poslední schůzky

**Comment by AnnaCajthamlova** [comment]
Díky. Číslo se vygenerovalo automaticky u všeho jako "1" a je editovatelné, pokud vidím dobře. Při testování prosím všechny, aby na to pamatovali a číslo výtisku doplňovali

**Comment by albertoh** [comment]
Na spravnem generovani cisla vytisku jeste pracuju.
Problem je zpusoben rozdilne vyznamy podpole "i"

**Comment by albertoh** [comment]
Zaviram tenhle issue
