### ISSUE TITLE
zobrazení záznamu při vyhledávání

### ISSUE THREAD

**Issue by AnnaCajthamlova** [NKCR-INPROVE/evidence.periodik#21]
Měla by existovat možnost otevřít si katalogizační záznam daného periodika, aby bylo možno ověřit př. rozsah vydávání.

**Comment by ludvicekj** [comment]
měl by to být záznam pro jednotlivé knihovny umístěný v hlavičce patřičného sloupce. 
![img1](https://user-images.githubusercontent.com/40558551/42573023-4f62834a-851b-11e8-9907-19a3c809c63c.png)

**Comment by albertoh** [comment]
A informace o odkazu bude na urovni titulu, vytisku nebo exemplare?

**Comment by ludvicekj** [comment]
titulu. podobně jako lze zobrazit zdrojový záznam u vdk
![img1](https://user-images.githubusercontent.com/40558551/43124049-43046522-8f26-11e8-98eb-c6880d779a0e.png)

**Comment by albertoh** [comment]
Tam je to na urovni harvestu. Je odkaz odkud se danni zaznam importoval.
Tituly se po harvestu algoritmicky slucujou, ne vzdycky spravne. 
Tady mame "jen" tituly, a vytisky, ktere nemaji informaci o vlastniku. Vlastnik je na konkretni exemplar (fizyckou jednotku), identifikovan carovym kodem.
 Na urovni vytisku je pole id_bib_zaznamu, tj identifikator bib. zaznamu. Ale je jen jeden. 
 Mohli bychom ho udelat opakovatelni, aby bylo mozne mit pro kazdeho vlastnika.
 A nebo pridat ho pro kazdy exemplar.

**Comment by pavelkocourek** [comment]
Přidat odkaz k identifikátoru (link)
