### ISSUE TITLE
zobrazení měsíce-roku-seznamu

### ISSUE THREAD

**Issue by ludvicekj** [NKCR-INPROVE/evidence.periodik#22]
ve vyhledávání při zobrazení měsíce nefunguje přepínání mezi zorbrazením měsíce, roku a seznamu.
![img1](https://user-images.githubusercontent.com/40558551/42572598-0f64349c-851a-11e8-9fd8-7d58616acaa0.png)

**Comment by AnnaCajthamlova** [comment]
zobrazení měsíce a roku funguje, chybí tlačítko na návrat k původnímu zobrazení (seznamu)
