### ISSUE TITLE
Chybné exempláře VKOL 

### ISSUE THREAD

**Issue by barinovak** [NKCR-INPROVE/evidence.periodik#23]
únor-duben 1936:
	únor 2650480929 (objevuje se pouze 1. 2. 1936, zbytek chybí)
	březen 2650480903 (chybí úplně)
	duben 2650480904 (objevuje se pouze 1. 4. 1936, zbytek chybí)
červenec-září 1936:
	vedle odpovídajícího čárového kodu 2650481625 (ČVC-ZÁŘÍ) je uváděn i čárový kod předešlého  časového úseku 2650481623 (KVĚT-ČVN)
	září neodpovídá čárový kod, má být 2650481625  
říjen-prosinec 1936:
	říjen 2650365268 (odpovídající čárový kod uveden pouze u 1. 10. 1936, zbytek měsíce neodpovídá, použit 2650481623 (KVĚT-ČVN))
	listopad 2650481624 (uveden chybný čárový kod 2650481623 (KVĚT-ČVN)) 
	prosinec 2650482449 (odpovídající čárový kod uveden pouze u 1. 12. 1936, zbytek měsíce neodpovídá, použit 2650481623 (KVĚT-ČVN))

**Comment by albertoh** [comment]
To same jako #18
