### ISSUE TITLE
Pořadí sloupců

### ISSUE THREAD

**Issue by habetpet** [NKCR-INPROVE/evidence.periodik#25]
Navrhujeme následující pořadí sloupců: 1. datum, 2. specifikace dne v týdnu, 3. specifikace vydání (ranní,...), 4. číslo výtisku, další sloupce budou zahrnovat údaje pro exempláře jednotlivých knihoven a to počet stran, čárový kód (?), signaturu, poznámku o stavu (poškození, mutace?). Tyto údaje se budou opakovat pro každý exemplář.

**Comment by Foltom** [comment]
Už bylo řešeno v rámci #20 - ve kterém byl zapracován stav dohodnutý na poslední schůzce. Viz citace ze zápisu: 
"potřebné úpravy:
o	tabulka jen pro konkrétní titul – ne
	tabulka jako celek – po vyfiltrování titulu zmizí sloupec název
	následně vyfiltrování mutace – mizí sloupec mutace
	přidat filtr „od-do“
	volba počtu řádků
o	druhý sloupec datum
o	vydání
o	číslo 
o	počet stran
-	údaje horizont:
o	návrh Korhoň prošel – př. záhlaví MZK, rozpadá se na signatury, pod tím čárové kódy exemplářů v jednom sloupci
-	příznak kompletní x nekompletní
-	sloupec pro strany u výtisku"

Takže teď bych další úpravy tabulky nerealizoval a otestoval využitelnost stávající podoby sloupců na Lidových novinách 1936, jež jsou v PerMonikovi naimportovány. Další úpravy až po testování - tj. po schůzce, kdy si výsledky testů ústně probereme.

**Comment by pavelkocourek** [comment]
Dohodnuto na schuzce 22.10.
**Pořadí sloupců  v tabulce :** 
1. Datum vydání
2. Vydání
3. Číslo
4. Počet stran
5. Celkem

**Exemplář** 
Bude zobrazen Stav namísto Poznámky:
- nekontrolováno `-`
- kontrola ok  `V`
. fyzicky poškozeno `!`
+ chybí strany `X`

Zesvětlit barevnost sloupce kvůli čitelnosti
