### ISSUE TITLE
Rozpis stran výtisku

### ISSUE THREAD

**Issue by habetpet** [NKCR-INPROVE/evidence.periodik#26]
Některé údaje o stavu exempláře budou platné pouze pro konkrétní stranu a měla by být možnost je na tuto stranu připojit.

**Comment by albertoh** [comment]
Nerozumim tomu. Co znamena " na tuto stranu připojit" ? V aplikaci mame vytisky a seznam exemplaru k nemu. Stranky nejsou.

**Comment by habetpet** [comment]
Každou stranu exempláře by mělo být možné detailně popsat. Prosím o vyjádření ostatních, ale možná by bylo dobré uvést reálný počet stran u každého exempláře vedle/místo čárového kódu. Tento počet by byl rozklikávací a vedl by na podrobný popis každé strany.

**Comment by Foltom** [comment]
K poli "Počet stran" bude přidáno tlačítko rozbalující menu s možností editace struktury stran.

**Comment by ludvicekj** [comment]
při změně počtu stran na vyšší číslo, se u již zpracovaných exemplářů označí správně nové strany jako chybějící, šlo by také udělat to, aby se Stav exempláře změnil z Kompletní na Chybí strany?

![img4](https://user-images.githubusercontent.com/40558551/49947542-ccb83d80-fef1-11e8-8a6d-990026d64dfd.png)

**Comment by pavelkocourek** [comment]
zavřeno na schuzce 7.3. NK
