### ISSUE TITLE
Přihlašování

### ISSUE THREAD

**Issue by AnnaCajthamlova** [NKCR-INPROVE/evidence.periodik#27]
Prosím o poslání přihlašovacích údajů. 
Díky

**Comment by Foltom** [comment]
Prosím o zaslání přihlašovacích údajů dle komentářů A. Cajthamlové. Bez toho nelze pokročit v testování. Díky. TF

**Comment by lucka-pavlova** [comment]
Omlouvám se za prodlevu. Alberto je do 20.8. na dovolené.

**Comment by albertoh** [comment]
Pro testovani, prihlasovaci udaje mame test/test
