### ISSUE TITLE
stazeni zaznamu a jednotek

### ISSUE THREAD

**Issue by Chlupova** [NKCR-INPROVE/evidence.periodik#30]
v Alephu v Opacu mame skyty zaznam Lidovych novin v tistene podobe, protoze pujcujeme ctenarum pouze mikrofilmy. Tim padem se nam zrejme tento exemplar nezobrazuje, mame zaznam odkryt neboli zrusit Skryto? Nebo lze stahnout i tak pokud budete tento priznak znat? Je uvedeno v poli MZK podpole s SKRYTO.
Diky
Radka a Vera

**Comment by pavelkocourek** [comment]
Ukončeno CDH Olomouc 5.6.
