### ISSUE TITLE
Změna číslování 

### ISSUE THREAD

**Issue by korhon** [NKCR-INPROVE/evidence.periodik#37]
Při procházení fyzického exempláře jsme zjistili, že obsahuje mnohem víc vydání než předem vygenerovaná struktura. Např dvě vydání za den (ráno a k poledni) nebo nedělní vydání.
Vydání lze doplnit ručně, ale pak by bylo vhodné, aby se vždy všechna další čísla v rámci roku přečíslovala o jedno. Už teď čísla neodpovídají. např. u 22. února máme v permonikovi č. 47, ve skutečnosti ale tento den vyšla čísla 95 (ranní) a 96 (k poledni).

**Comment by Foltom** [comment]
Na základě workshopu v Brně je tento požadavek uznán jako validní. Prosím o upravení.

**Comment by pavelkocourek** [comment]
Příklad : přidání "nedělního vydání" doprostřed řady čísel - je třeba funkce VLOZIT CISLO (nebo UBRAT CISLO)  a přečíslovat zbývající do konce řady
