### ISSUE TITLE
Založení nového ročníku

### ISSUE THREAD

**Issue by korhon** [NKCR-INPROVE/evidence.periodik#38]
Pro založení nového ročníku by možná bylo dobré mít k dispozici nástroj pro generování nového ročníku. 
V něm by se dalo předem zvolit, v jaké dny titul vycházel, případně v kolika vydáních. Pak by hned vznikla struktura odpovídající skutečnosti.

**Comment by pavelkocourek** [comment]
Doplit zadání

**Comment by pavelkocourek** [comment]
Je třeba doplnit zadání

**Comment by pavelkocourek** [comment]
Požadavek je možnost vytvořit týden manuálně a ten dát klonovat  (včetně opakovaných "dopoledních"  + "večerních")  vydání.
Bude prodiskutování na schůzce.

**Comment by pavelkocourek** [comment]
Nahrazuje #68 
CDH Olomouc 5.6.
