### ISSUE TITLE
Vytvoření ikony na vstupní plochu "Kompletní s upozorněním"

### ISSUE THREAD

**Issue by Foltom** [NKCR-INPROVE/evidence.periodik#44]
Vložit novou ikonu pro případy, že dokument je kompletní, ale má nějaká další specifika (například dokument je kompletní, ale má navíc omylem vloženou přílohu z jiného data). Ikona bude mít podobu jako kompletní, ale pole pod "fajfkou" bude oranžové.

**Comment by pavelkocourek** [comment]
Uzavřeno na schůzce v NK 7.3:
