### ISSUE TITLE
označení mutací vydání

### ISSUE THREAD

**Issue by Foltom** [NKCR-INPROVE/evidence.periodik#46]
k exempláři přidat pole "označení regionálního vydání" - vkládání symbolů - př hvězdička, puntík - zobrazení v přehledové tabulce
plus k tomu pole "popis vydání" - ruční doplnění popisu vydání
v popisu doplnit, jak je daná mutace označena

**Comment by Foltom** [comment]
Označení reginonální mutace (hvězdičky, puntíky v různých počtech) musí být zobrazeno i v poli knihovny, za informací za čárovým kódem.

**Comment by pavelkocourek** [comment]
Uzavřeno na schůzce v NK 7.3.
