### ISSUE TITLE
Způsob označení mutace

### ISSUE THREAD

**Issue by Foltom** [NKCR-INPROVE/evidence.periodik#47]
K exempláři přidat pole "Označení regionálního vydání". Toto pole bude omezeně editovatelné předpřipravenými znaky /například * nebo • nebo +/. Bude se doplňovat pouze počet těchto znaků, které budou určovat o jakou mutaci se jedná. Pod tím bude pole "Popis označení mutace", které bude volně editovatelné a bude popisovat případný zjištěný rozdíl. V přehledové tabulce bude u vydání přidáno pole "Způsob označení mutace", kde bude vložen výše uvedený znak, aby bylo vidět, čím bylo vydání popisováno.

**Comment by pavelkocourek** [comment]
Uzavřeno na schůzce v NK 7.3.
(požadavek na případné zobrazení v tabulce bude doplněno do samostatného Issue)
