### ISSUE TITLE
nedostupná aplikace

### ISSUE THREAD

**Issue by ludvicekj** [NKCR-INPROVE/evidence.periodik#48]
aplikace nejde vůbec načíst. 
prohlížeč ukazuje hlášení: "Vaše připojení k internetu je blokováno. Připojení mohlo být zablokováno firewallem nebo antivirovým softwarem." ale na počítači se žádné nastavení neměnilo..

**Comment by albertoh** [comment]
To asi je mimo aplikace. Nevim jak muzu pomoct

**Comment by ludvicekj** [comment]
ano, toho jsme se trochu obával.. ale zdá se, že už vše funguje
