### ISSUE TITLE
počet stran u editace exempláře

### ISSUE THREAD

**Issue by AnnaCajthamlova** [NKCR-INPROVE/evidence.periodik#49]
u čísla 1 jsme upravili a specifikovali počet stran, následně při editu exempláře se zobrazují špatně checkboxy pro výběr stran.
![per-alberto](https://user-images.githubusercontent.com/34305869/49584107-847da600-f95a-11e8-85c9-213b3888af23.png)

**Comment by albertoh** [comment]
Opraveno
