### ISSUE TITLE
Zaznačení poškozených stran

### ISSUE THREAD

**Issue by Foltom** [NKCR-INPROVE/evidence.periodik#50]
Zaznačení chybějících a poškozených stran musí být ve stavu exempláře zvlášť (poškozené stran x chybějící strany x degradece) a každému musí být možné separátně přiřadit strany.

**Comment by pavelkocourek** [comment]
Oddělit "poškozené" a "chybějící" - sada checkboxů má být pro každý zvlášť

**Comment by pavelkocourek** [comment]
CDH Olomouc 5.6.
MK doplni do návrhu
