### ISSUE TITLE
Zpětná šipka

### ISSUE THREAD

**Issue by Foltom** [NKCR-INPROVE/evidence.periodik#53]
Zpětná šipka vrací na hlavní tabulku - aby šlo přeskakovat mezi editací hlavní tabulky a jednotlivých formulářů.

**Comment by pavelkocourek** [comment]
Prosím rozepsat jak se má chovat.
Z jake stranky do jake stranky? Nebo z formulare do jakeho formulare?
Šipka Zpět v browseru vrací o jednu stranku. Má-li se to chovat jinak, musime menit url mezi strankami, formuláři, atd.

**Comment by ludvicekj** [comment]
fungovat by mělo tak, jako to dělá toto tlačítko z pohledu kalendáře: 
![img5](https://user-images.githubusercontent.com/40558551/54918940-c88fb900-4eff-11e9-843b-115715bb899b.png)

ale přímo ze stránky editace čísla. takže by tam u tlačítka, které přepíná do pohledu kalendáře, bylo ještě jedno, které přepne na hlavní tabulku: 
![img6](https://user-images.githubusercontent.com/40558551/54919167-62effc80-4f00-11e9-9c79-174846638fe3.png)
