### ISSUE TITLE
změna Stavu při změně počtu stran

### ISSUE THREAD

**Issue by ludvicekj** [NKCR-INPROVE/evidence.periodik#54]
při změně počtu stran na vyšší číslo, se u již zpracovaných exemplářů označí správně nové strany jako chybějící, šlo by také udělat to, aby se Stav exempláře změnil z Kompletní na Chybí strany?

![img4](https://user-images.githubusercontent.com/40558551/49947542-ccb83d80-fef1-11e8-8a6d-990026d64dfd.png)

_Originally posted by @ludvicekj in https://github.com/NKCR-INPROVE/evidence.periodik/issues/26#issuecomment-447003325_

**Comment by pavelkocourek** [comment]
Prosím popsat stavy provázanosti mezi označenými poli
