### ISSUE TITLE
vložení nového záznamu - mladá fronta

### ISSUE THREAD

**Issue by ludvicekj** [NKCR-INPROVE/evidence.periodik#55]
pokusil jsem se vložit nový záznam Mladé fronty k dalšímu testování. což se úspěšně povedlo, ovšem když jsem se ho pokusil naklonovat- nejdříve čísla na celý měsíc a poté čárové kódy, přestalo se v tabulce cokoliv zobrazovat.
na domovské stránce se ale u MF - Praha ukazuje údaj "31 záznamů"..

**Comment by albertoh** [comment]
Opraveno

**Comment by pavelkocourek** [comment]
Uzavřeno na schůzce NK 7.3.
