### ISSUE TITLE
prázdná hodnota vydání

### ISSUE THREAD

**Issue by AnnaCajthamlova** [NKCR-INPROVE/evidence.periodik#57]
MF nemá vydání ranní x večerní, hodnota je tedy prázdná, pokud se nevyplní, v tabulce se zobrazí "record.publication.". Prosím přidat hodnotu "bez určení".

**Comment by albertoh** [comment]
Opraveno

**Comment by pavelkocourek** [comment]
hodnota chybí ve fasetách  "bez určení"
