### ISSUE TITLE
Fasety - pořadí

### ISSUE THREAD

**Issue by AnnaCajthamlova** [NKCR-INPROVE/evidence.periodik#58]
1. datum - zůstává 
2. titul - přejmenovat na "metatitul"
3. název na titulní straně 
4. mutace (Praha x Brno, atd.)
5. mutační vydání (hvězdičky)
6. vydání (ranní x večerní atd.)
7. vlastník
8. stav

Všechny fasety by měly být trvale rozkliknuté

**Comment by ludvicekj** [comment]
![meta-titul-vložení nového záznamu](https://user-images.githubusercontent.com/40558551/56346192-e16b5180-61c1-11e9-992a-0fd40ca57c9d.png)
![hvězdičky-exemplář](https://user-images.githubusercontent.com/40558551/56346194-e4664200-61c1-11e9-96e3-da115ae36765.png)

**Comment by albertoh** [comment]
opraveno

**Comment by pavelkocourek** [comment]
Pořadí - Prohodit prosím Vydani a Mutacni vydani
