### ISSUE TITLE
označení mutačního vydání exempláře

### ISSUE THREAD

**Issue by AnnaCajthamlova** [NKCR-INPROVE/evidence.periodik#59]
za ČK přidat pole pro zobrazení hvězdiček, které označují konkrétní mutační vydání daného výtisku (musí se zobrazovat v tabulce)

**Comment by pavelkocourek** [comment]
CDH Olomouc 5.6
Mezi čárový kód a ikony (tlačítka) bude zobrazena mutace (hvězdičky) 
BUde řešeno po implementaci nového zadávání #68
