### ISSUE TITLE
Hodnocení stavu

### ISSUE THREAD

**Issue by AnnaCajthamlova** [NKCR-INPROVE/evidence.periodik#6]
Jednotlivé ukazatele stavu (jejich výběr) bude potřeba ještě prodiskutovat. Kryje se př. "není vůbec" a "chybějící celé číslo".

**Comment by Foltom** [comment]
Chybí vůbec se vypustí /místo toho zůstává "chybějící číslo", které bude mít ikonku na úvodní straně/; 
BUDE:
**CHYBÍ**
- chybí číslo
- chybí strana (bude možné doplnit číslo)
**- POŠKOZENO**
- poškozený dokument (bude možné doplnit strany, bez určení typu poškození)
**DEGRADACE**
**CHYBNÁ PAGINACE
CHYBNÉ ČÍSLOVÁNÍ**
CHYBNĚ SVÁZÁNO
CENZUROVÁNO**
**CENZURNÍ VÝTISK**

**Comment by pavelkocourek** [comment]
zavřeno na schuzce 7.3. NK
