### ISSUE TITLE
Nastavení zobrazených sloupců

### ISSUE THREAD

**Issue by korhon** [NKCR-INPROVE/evidence.periodik#62]
Nebylo by možné v celkové tabulce všech exemplářů přidat možnost volby zobrazených sloupců? Například nechci vidět počet stran, nechci vidět muří nohy u mutace, nechci ranní nebo polední vydání. 
Případně vůbec nemusím chtít vidět Nk a MZK, ale např jenom exempláře z VKOL

**Comment by pavelkocourek** [comment]
CDH Olomouuc 5.6 - bude řešit ukotvení sloupců

**Comment by albertoh** [comment]
Vyreseno v ramci #101
