### ISSUE TITLE
Zvýraznění řádků

### ISSUE THREAD

**Issue by korhon** [NKCR-INPROVE/evidence.periodik#63]
U exemplářů na konci tabulky (VKOL) je velmi složité udržet informaci, k jakému dni se vztahují. Nešlo by přidat možnost zvýraznění řádku, případně střídat barvy řádků, aby se usnadnila orientace?

**Comment by zabak** [comment]
Zvýrazňoval bych nějak ne jednotlivé řádky ale společně řádky z jednoho dne - když je víc vydání, tak aby bylo vidět co patří do stejného dne. Třeba tlustší oddělovací čarou nebo zašednutím sudých řádků. 

Navíc ale by z důvodu lepší práce mělo být možné měnit pořadí knihoven a případně skrýt některé knihovny podobně jako sloupce v excelu. Protože až přidám čtvrtou knihovnu, tak už se na monitor nevejde. A když použiju scrollbar, tak se první skryje sloupec s daty, který by měl naopak být pořád vidět.

**Comment by pavelkocourek** [comment]
CDH Olomouc 5.6.
Ukotvit první část sloupců (Mutace-Celkem)
Barevné odlišení knihoven zrušit.
Pruhované dny v tabulce. (jeden nebo více řádků)

**Comment by albertoh** [comment]
Vyreseno v ramci #101
