### ISSUE TITLE
Čárový kód

### ISSUE THREAD

**Issue by korhon** [NKCR-INPROVE/evidence.periodik#64]
Čárové kódy zabírají v tabulce mnoho místa, přivítali bychom checkbox, který by zapínal a vypínal jejich zobrazení. Na první pohled by měl být vidět spíš informace o mutačním vydání (** nebo • případně jiný znak)

**Comment by korhon** [comment]
Informace o čárových kódech je samozřejmě důležitá, ale možná by k tomu mohl sloužit "pohled" do databáze, který ukáže, která čísla jsou v kterých svazcích uchována. Např. funkce "Zobraz fyzické svazky", která bude sloužit jako další způsob zobrazení vedle tabulky a kalendáře

**Comment by zabak** [comment]
Nebo by mohl být čárový kód reprezentován jen malou ikonkou nad kterou když najedu, tak se mi zobrazí.

**Comment by zabak** [comment]
Vrátíme se k tomu později, teď zavřít.
