### ISSUE TITLE
Chybějící čísla

### ISSUE THREAD

**Issue by korhon** [NKCR-INPROVE/evidence.periodik#67]
V případě, kdy v daném svazku knihovny chybí nějaké číslo (výtisk novin), pak by pro přehlednost bylo lepší mít prázdné pole. Teď máme informaci o čárovém kódu s poznámkou, že číslo chybí, což je dost matoucí. Není přitom podstatné, jestli číslo vůbec nevyšlo nebo ho knihovna jen nemá (např. nebylo dodáno). Zkrátka není

**Comment by pavelkocourek** [comment]
CDH Olomouc 5.6.
V rozhraní je prázdná buňka v tabulce ( Příklad Mladá Fronta VKOL 265A003887 ) 
Po klonování je třeba promazat.
