### ISSUE TITLE
aktivní filtry - červené tlačítko

### ISSUE THREAD

**Issue by zabak** [NKCR-INPROVE/evidence.periodik#69]
Pokud nemám aktivní žádný filtr, tak stejně vidím nadpis aktivní filtry a navíc u něj červené talčítko, které nic nedělá. Velmi matoucí zvlášť v situaci, kdy pořádně nefunguje hledání

![image](https://user-images.githubusercontent.com/811537/58892809-3b32c700-86ef-11e9-81fa-9bf08a22b3b8.png)

**Comment by pavelkocourek** [comment]
CDH Olomouc 5.6.
Zobrazit řádek, jen když budou filtry

**Comment by albertoh** [comment]
Vyreseno v ramci #101
