### ISSUE TITLE
Filtrování - vlastník

### ISSUE THREAD

**Issue by Chlupova** [NKCR-INPROVE/evidence.periodik#7]
Při filtrování vlastnika zůstává více vlastníků i když vyberu jednoho

**Comment by albertoh** [comment]
Vydani muze mit vice exemplaru s vice vlastniku. 
Tim padem muze byt vice vlastniku, ikdyz je vybran jeden.
Pridal jsem ikonku odznacujici vybrane

**Comment by AnnaCajthamlova** [comment]
filtrování nefunguje

**Comment by pavelkocourek** [comment]
Zavřeno na schuzce 22.10. v CDH
