### ISSUE TITLE
Zprovoznit systém na vlastní doméně na https

### ISSUE THREAD

**Issue by zabak** [NKCR-INPROVE/evidence.periodik#72]
@Foltom Vzhledem k tomu, jak dlouho totéž trvalo u VDK tak prosím začni domlouvat aby ten server dostal doménové jméno, certifikát a rozjelo se to celé na https.

**Comment by zabak** [comment]
Jaká je pokrok v této věci za poslední rok? Tohle je věc, kterou v MZK řešíme skoro obratem.

**Comment by AnnaCajthamlova** [comment]
vyřešeno
