### ISSUE TITLE
menu v záhlaví

### ISSUE THREAD

**Issue by zabak** [NKCR-INPROVE/evidence.periodik#76]
Volba Domovská stránka je duplicitní s názvem evidence periodik vlevo. Navrhuji volbu odstranit. Volba English nic nedělá, ale ve zdrojáku anglická verze existuje. Nutno opravit nebo odstranit položku z menu, pokud angličtinu nechceme. 
Volba vložit záznam u nepřihlášenho uživatele by měla být zašedlá nebo skrytá.

**Comment by pavelkocourek** [comment]
CDH Olomouc 5.6.  
Prozatím vynechat angličtinu

**Comment by zabak** [comment]
Angličtina funguje. V menu ale zůstává volba Home, která měla být odstaněna! Na levé straně je nápis EP | domovská stránka, ale aktivní je jen EP, nápis domovská stránka by měl být také klikatelný.

**Comment by Chlupova** [comment]
Je pořád

**Comment by zabak** [comment]
proklikal jsem to a myslím, že takto to má logiku, i když to není přesně tak jak jsem původně navrhoval - zavírám.
