### ISSUE TITLE
překlady

### ISSUE THREAD

**Issue by zabak** [NKCR-INPROVE/evidence.periodik#78]
Zadal jsem jako pull requesty nějaké opravy překladů, ale všiml jsem si, že jsou tam položky, které zatím v jazykových souborech vůbec nejsou. Prosím tyto položky do jazykových souborů doplnit.

**Comment by pavelkocourek** [comment]
Prosím napsat pro A příklad
CDH Olomouc 5.6.

**Comment by Foltom** [comment]
@zabak prosím uveď.

**Comment by Foltom** [comment]
Viz pull request výše!

**Comment by zabak** [comment]
"Svazek" v hlavním menu, všechna záhlaví sloupců v editaci svazku, modrá tlačítka v editaci svazku, ve fasetách se objevuje record.StavIssue.ChVV, org.json.JSONArray:["VKOL","MZK","MZK","MZK","NKP"], položky ve fasetě "State", název fasety "Název na titulní straně"
