### ISSUE TITLE
editace údajů

### ISSUE THREAD

**Issue by frrezek** [NKCR-INPROVE/evidence.periodik#79]
V pravé části generovací tabulky (tabulka "Svazek") je potřeba možnost u jednotlivých čísel změnit ručně údaje "počet stran" a "vydání" - počet stran se může lišit v každém čísle; při přidání dalšího vydání v jednom dni je potřeba možnost označit, o jaké vydání se jedná

**Comment by ludvicekj** [comment]
také by měl jít změnit údaj "mutační vydání"


![issue#79](https://user-images.githubusercontent.com/40558551/68470753-00dcd100-021d-11ea-89d1-5eea042f0fac.png)
