### ISSUE TITLE
Lidovky 1936

### ISSUE THREAD

**Issue by AnnaCajthamlova** [NKCR-INPROVE/evidence.periodik#8]
Prosím o stažení Lidových novin Brno 1936 do Permoníka pro účely testování

**Comment by albertoh** [comment]
Muzete mi poslat identifikator v alephu?

**Comment by AnnaCajthamlova** [comment]
ADM 1308889 BIB 1282114

**Comment by albertoh** [comment]
Pridal jsem.
Ale zaznam v vdk-set je tezko zpracovatelny: podpole "i" v pole 996 nema unikatni vyznam. pokazde je jiny, a navic nezrozumitelny.
