### ISSUE TITLE
odkaz na tabulku

### ISSUE THREAD

**Issue by frrezek** [NKCR-INPROVE/evidence.periodik#81]
Bylo by dobré do generovací tabulky přidat odkaz do "původní" tabulky, kde se zobrazují všechny exempláře - po vygenerování se mohu podívat, jak se svazek zobrazí; nyní se tam dostanu pouze přes Domovskou stránku

**Comment by ludvicekj** [comment]
obdobné ikony, jaké se řešily v #53 

![issue#81](https://user-images.githubusercontent.com/40558551/68471283-23231e80-021e-11ea-8806-eb1661cd1f53.png)

**Comment by Foltom** [comment]
Ikona editovat issues nevede do definovaného cíle. Má vést do tabulky exemplářů - viz obrázek.

**Comment by albertoh** [comment]
Pridat tlacitko "zobrazit v tabulce" na strance editaci svazku, vedle (i) "prehled svazku"
