### ISSUE TITLE
přidání dalšího vydání

### ISSUE THREAD

**Issue by frrezek** [NKCR-INPROVE/evidence.periodik#82]
Pokud v pravé části generovací tabulky přidáme pomocí symbolu "+" další vydání v jednom dni, nechceme, aby se zkopírovaly i všechny údaje o chybějících/poškozených stranách atd.

**Comment by ludvicekj** [comment]
![issue#82](https://user-images.githubusercontent.com/40558551/68471624-dbe95d80-021e-11ea-8f15-b08bca85d0dd.png)
