### ISSUE TITLE
přílohy

### ISSUE THREAD

**Issue by ludvicekj** [NKCR-INPROVE/evidence.periodik#85]
spíše k širší diskuzi: 

označení příloh v tabulce "Svazek" je, myslím, dobré. problém je, že mimo tuto tabulku to není vidět (ani označení, že jde o přílohu, ani název přílohy). 

kde a jak by se to mělo zobrazovat?

mělo by to asi být vidět už v hlavní tabulce a fasetách
![issue#85-2](https://user-images.githubusercontent.com/40558551/68473167-831bc400-0222-11ea-88af-3939e945997a.png)

nebo k tomu využít pole Název a podnázev v editaci čísla?
![issue#85](https://user-images.githubusercontent.com/40558551/68472999-1ef90000-0222-11ea-9b68-8d1021e18ba6.png)

**Comment by zabak** [comment]
- Příloha nebude vedena jako zatržítko, ale půjde o jeden druhů vydání. Toto se musí změnit i v databázi. Nebude samostatná položka název přílohy, ale pro přílohu se bude používat normální pole název a podnázev.
**U tabulky editace svazku:**
- U šablony se zruší sloupec toto je příloha, sloupec název přílohy bude název, přidá se i sloupec podnázev.
- v části vpravo : zúžit sloupec mutace, cenzurováno a název. Přidat sloupec podnázev.
**U zobrazovací tabulky:**
Zúžit sloupce mutace, datum vydání a vydání a přidat sloupec název

**Comment by pkudela** [comment]
hotovo,  bude dostupne po nasazeni nove verze, predavam @albertoh

**Comment by ludvicekj** [comment]
za mě funguje.
pokud k tomu nikdo nic nemá, uzavřu..
