### ISSUE TITLE
automatické přečíslování

### ISSUE THREAD

**Issue by korhon** [NKCR-INPROVE/evidence.periodik#87]
Ve sloupci "Číslo" je nutné mít k dispozici volitelnou funkci automatického číslování. Při vygenerování struktury se vytvoří čísla pro všechny dny, kdy by titul měl vyjít, ale např. v případě státních svátků noviny nevycházely, vydání z toho dne se zruší a číslování se musí u všech dalších čísel o jedno číslo posunout. Automatické to být nemůže, protože některá jiná čísla se budou vynechávat jen proto, že ve svazku z nějakého důvodu chybí.

**Comment by zabak** [comment]
Kliknutím pravým tlačítkem na číslo se objeví dialog s nabídkou seznamu existujících vydání. Zaškrtnu ta vydání, která dohromady tvoří jednu číselnou řadu. Ani jeden druh vydání nebude defaultně zaškrtnutý. Kliknu na přečíslovat a přečíslují se mi všechny zatržené vydání jednou číselnou řadou počínaje tím číslem, na které uživatel kliknul. Nezatržená vydání se nepřečíslují.

**Comment by pavelkocourek** [comment]
Přidáme ikonu vedle čísla (šipka dolu) - a pak podle předcházejícího textu.
(Příklad je přečídlovávám od č.250 dál .. ale bez Příloh)

**Comment by korhon** [comment]
Přečíslování je nezbytné! Nešlo by podobně jak píše Petr, vedle čísla přidat nalevo "-" a napravo "+", které změní číslo výtisku i všech dalších za ním o jedno, případně o tolik, kolikrát na něj kliknu?
