### ISSUE TITLE
Svazek - uprava vzhledu 

### ISSUE THREAD

**Issue by pkudela** [NKCR-INPROVE/evidence.periodik#88]
Doslo k uprave vzhledu stranky svazek a nekterych souvisejicich komponent. Data v tabulce se oproti predchozi verzi uzivatelsky zprehlednila viz. screenshoty nize a strucny seznam uprav:
---

- prizpusobeni velikosti pisma v tabulce vcetne velikosti ikon
- sjednoceni ikon vcetne barevnosti
- fixni delka pro nektere bunky tabulky
- zvyrazneni bunek tabulky, ktere jsou mozne editovat
- zvyrazneni bunky, pokud je bunka editovana
- obecne zmeny nekterych barev
- odliseni buttonu pokud je ve stavu disable / uzivatel neprihlasen
- zmena html / scss - vycisteni kodu
- vytahnuti nekterych dulezitych vlastnosti do konfiguracniho _app-variables.scss
---
**Svazek pred upravami**
![image](https://user-images.githubusercontent.com/16591052/69039946-3b98f300-09ed-11ea-979a-6d37a7e81914.png)

---
**Svazek po urpavach**
![image](https://user-images.githubusercontent.com/16591052/69039777-e2c95a80-09ec-11ea-88c8-312baf52a2de.png)
![image](https://user-images.githubusercontent.com/16591052/69039846-068ca080-09ed-11ea-801c-9db60a7c5d7c.png)
![image](https://user-images.githubusercontent.com/16591052/69040112-86b30600-09ed-11ea-9f62-2138f7fa7050.png)
![image](https://user-images.githubusercontent.com/16591052/69040159-9c283000-09ed-11ea-9509-35ace40095dc.png)
![image](https://user-images.githubusercontent.com/16591052/69040200-b6faa480-09ed-11ea-9492-1b610363b0c4.png)

**Comment by pkudela** [comment]
@albertoh prosim o nasazeni na server k otestovani

**Comment by Foltom** [comment]
Připomínky jsou v rámci dalších issue.
