### ISSUE TITLE
Točítko (přesýpací hodiny)

### ISSUE THREAD

**Issue by zabak** [NKCR-INPROVE/evidence.periodik#92]
Pokud zodpovězení dotazu trvá déle, mělo by se zobrazit nějaké točítko, aby bylo jasné, že stroj pracuje - teď není poznat, kdy už je stroj hotový a kdy jen chroustá.

**Comment by albertoh** [comment]
Prazdny svazek ne schovava progress bar

**Comment by albertoh** [comment]
Zavreno na schuzce 16.06
