### ISSUE TITLE
Když kliknu na čárový kód, měl by se zobrazit přehled daného svazku

### ISSUE THREAD

**Issue by zabak** [NKCR-INPROVE/evidence.periodik#94]

**Comment by zabak** [comment]
Rozsah dní, statistiku mutací, mutačních vydání, vydání, informaci jestli je kompletní a výpis chybějících čísel, chybějících a poškozených stran, atd.

**Comment by zabak** [comment]
Dodáme tabulku jak to má vypadat: https://docs.google.com/document/d/1gRqRNSK_vO5N80qC3VM97-lNI2Qj91eTEZ3UcLPXGEY/edit?usp=sharing

**Comment by korhon** [comment]
Koncept doplněn

**Comment by albertoh** [comment]
Pridat link v tabulce

**Comment by ludvicekj** [comment]
funguje. myslím, že se může zavřít.
