### ISSUE TITLE
Pojmenovat obrazovky

### ISSUE THREAD

**Issue by pavelkocourek** [NKCR-INPROVE/evidence.periodik#95]
Do zeleného řádku doplnit texty :
Evidence periodik - přehled exemplářů
Evidence periodik - editace svazku
Evidence periodik - editace issue
Vyhledávací pole bude zarovnáno s boxem s tabulkou

**Comment by albertoh** [comment]
Evidence periodik - editace issue ->
Evidence periodik - editace vytisku
