### ISSUE TITLE
Editace vstupních dat - metatitul

### ISSUE THREAD

**Issue by pavelkocourek** [NKCR-INPROVE/evidence.periodik#96]
Metatitul zakládá (mění/maže) jenom supersprávce (nemusí být editovatelné v rozhraní)
Titul zakládá instituce 

Kristýna doplní seznam metatulůg pro založení.

**Comment by barinovak** [comment]
Rovnost
Svobodné slovo
Práce
Lidová demokracie
Rudé právo
Zemědělské noviny
Československý sport
Hospodářské noviny

**Comment by albertoh** [comment]
Nove metatituly zalozene. Pridana nova stranka pro editace metatitulu

**Comment by zabak** [comment]
já teda ty nově založené metatituly nevidím (nevím jestli hraje roli že nejsem přihlášený, resp. že jsou zatím prázdné)

**Comment by zabak** [comment]
Bude potřeba pročistit stávající metatituly, aby tam zbyly jen ty produkční. Mimo to, může být jeden nebo dva testovací, ale měli bychom se dohodnout, že mimo ty testovací metatituly už budou všude jen ostrá data. Mj. tedy musíme říct, co ze stávajících dat by se mělo vymazat a zadat znova.

Mimo to je nutné sebrat všem možnost založit metatitul a nechat to jen adminovi, nebo tu funkci z grafického rozhraní zcela odstranit a do dokumentace jen napsat jak se to přidává a maže. Mazání by ale mělo být nějak konzistentní, tj. s kontrolou, že nemažu omylem produkční metatitul.

**Comment by zabak** [comment]
Kdo má právo pročistit ty metatituly?

**Comment by AnnaCajthamlova** [comment]
#139

**Comment by zabak** [comment]
Vyřešeno
