### ISSUE TITLE
Správa uživatelů

### ISSUE THREAD

**Issue by pavelkocourek** [NKCR-INPROVE/evidence.periodik#97]
povolení google účtu pro aplikaci

**Comment by pavelkocourek** [comment]
+ je třeba prodloužit čas odhlašování

**Comment by zabak** [comment]
> * je třeba prodloužit čas odhlašování

na cca 8 hodin

**Comment by albertoh** [comment]
Pridana zakladni sprava uzivatelu.
Existuje jeden uzivatel "admin", ktery ma moznost zakladat dalsi.
Pri zakladanni noveho uzivatele, vychozi heslo je test. Toto heslo kazdy uzivatel muze menit v svem uzivatelskem uctu "profil uzivatele"

**Comment by Foltom** [comment]
Prosím @albertoh, kdo má tyto administrátorská práva? Měli bychom to postupně přesunout do módu "Průzkum fondů", kdy má tyto superadmin práva pro přidělování osob pracovník NK ČR (v případě průzkumu D. Hřebecká). MZK by chtěla nyní vytvořit konkrétní účty pro P. Žabičku, V. Jelínkovou a R. Chlupovou. Podobně bychom měli postupovat i v rámci NK a VKOL. Osobně bych chtěl, aby se toho ujala Anička @AnnaCajthamlova? Jak to vidíte?

**Comment by AnnaCajthamlova** [comment]
> Prosím @albertoh, kdo má tyto administrátorská práva? Měli bychom to postupně přesunout do módu "Průzkum fondů", kdy má tyto superadmin práva pro přidělování osob pracovník NK ČR (v případě průzkumu D. Hřebecká). MZK by chtěla nyní vytvořit konkrétní účty pro P. Žabičku, V. Jelínkovou a R. Chlupovou. Podobně bychom měli postupovat i v rámci NK a VKOL. Osobně bych chtěl, aby se toho ujala Anička @AnnaCajthamlova? Jak to vidíte?

Když mi ukážete, jak se to dělá, tak klidně :)

**Comment by zabak** [comment]
přístupová práva vyřešena, zbytek issue zůstává

**Comment by AnnaCajthamlova** [comment]
- u mého účtu mi nefunguje změna hesla z test
- u účtu Františka Rezka nefunguje výchozí heslo test
- nedaří se mi přihlásit do účtu admina 
můžete se na to prosím podívat?

**Comment by albertoh** [comment]
Vycistil jsem uzivatelske ucty.
Uzivatelska jmena jsem zmenil tak, aby neobsahovala diakritiku:
Anna Cajthamlová -> cajthamlova
František Rezek -> rezek

Zkuste to
